version: '3.8'

services:
  # MySQL database service
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=SkiStationDB
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # Spring Boot application service
  ski:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 9091:9091
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/SkiStationDB?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: '*'
      MANAGEMENT_METRICS_PROMETHEUS_ENABLED: 'true'
      MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: always
      MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: 'true'
      MANAGEMENT_ENDPOINT_PROMETHEUS_SENSITIVE: false
      MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: 'true'
      MANAGEMENT_ENDPOINT_WEB_BASE_PATH: /actuator

volumes:
  mysql-data: