version: "3.8"
services:
  mysqldb:
    container_name: db-mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - db:/var/lib/mysql

  gestion-station-ski:
    container_name: gestion-station-ski
    image: krichen/gestion-station_ski:1.0
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    ports:
      - "8089:8089"
    stdin_open: true
    tty: true
volumes:
  db:

